# Generated by Django 6.0.1 on 2026-01-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0009_alter_datospersonales_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursocapacitacion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cursocapacitacion',
            name='fecha_finalizacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='cursocapacitacion',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='cursos/imagenes/', verbose_name='Vista Previa (Imagen JPG/PNG)'),
        ),
        migrations.AlterField(
            model_name='cursocapacitacion',
            name='certificado_pdf',
            field=models.FileField(blank=True, help_text='Sube el certificado del curso en formato PDF', null=True, upload_to='cursos/certificados/', verbose_name='Documento Oficial (PDF)'),
        ),
    ]
