# Generated by Django 6.0.1 on 2026-01-28 22:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0010_cursocapacitacion_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursocapacitacion',
            options={'ordering': ['-fecha_realizacion'], 'verbose_name_plural': 'Cursos y Formaciones'},
        ),
        migrations.AlterModelOptions(
            name='estudiorealizado',
            options={'ordering': ['-fecha_fin'], 'verbose_name_plural': 'Estudios Realizados'},
        ),
        migrations.AlterModelOptions(
            name='experiencialaboral',
            options={'ordering': ['-fecha_inicio'], 'verbose_name_plural': 'Experiencias Laborales'},
        ),
        migrations.AlterModelOptions(
            name='productolaboral',
            options={'ordering': ['-fecha'], 'verbose_name_plural': 'Productos Laborales'},
        ),
        migrations.AlterModelOptions(
            name='reconocimiento',
            options={'ordering': ['-fecha'], 'verbose_name_plural': 'Reconocimientos y Premios'},
        ),
        migrations.RemoveField(
            model_name='cursocapacitacion',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='cursocapacitacion',
            name='fecha_finalizacion',
        ),
        migrations.RemoveField(
            model_name='cursocapacitacion',
            name='imagen_portada',
        ),
        migrations.AddField(
            model_name='cursocapacitacion',
            name='fecha_realizacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cursocapacitacion',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_direccion_domiciliaria',
            field=models.BooleanField(default=False, help_text='Si está activo, se mostrará la dirección de casa en la web.'),
        ),
        migrations.AddField(
            model_name='datospersonales',
            name='mostrar_telefono',
            field=models.BooleanField(default=True, help_text='Mostrar teléfono celular en la web.'),
        ),
        migrations.AddField(
            model_name='estudiorealizado',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Mostrar en CV'),
        ),
        migrations.AddField(
            model_name='productolaboral',
            name='url_demo',
            field=models.URLField(blank=True, help_text='Link al proyecto en vivo si existe', null=True),
        ),
        migrations.AddField(
            model_name='productolaboral',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ventagarage',
            name='activo',
            field=models.BooleanField(default=True, help_text='Desactívalo para ocultarlo de la tienda sin borrarlo'),
        ),
        migrations.AlterField(
            model_name='cursocapacitacion',
            name='certificado_pdf',
            field=models.FileField(blank=True, help_text='Sube el certificado del curso en formato PDF', null=True, upload_to='cursos/certificados/'),
        ),
        migrations.AlterField(
            model_name='cursocapacitacion',
            name='horas',
            field=models.PositiveIntegerField(help_text='Cantidad de horas académicas'),
        ),
        migrations.AlterField(
            model_name='estudiorealizado',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Dejar vacío si sigues estudiando', null=True),
        ),
        migrations.AlterField(
            model_name='estudiorealizado',
            name='fecha_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Dejar en blanco si es el trabajo actual', null=True),
        ),
        migrations.AlterField(
            model_name='experiencialaboral',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='productolaboral',
            name='archivo',
            field=models.FileField(blank=True, help_text='Documentación del proyecto', null=True, upload_to='proyectos/archivos/'),
        ),
        migrations.AlterField(
            model_name='productolaboral',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='productolaboral',
            name='registro_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='item_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='stock',
            field=models.PositiveIntegerField(default=1, help_text='Cantidad disponible'),
        ),
    ]
