# Generated by Django 6.0.1 on 2026-01-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0011_alter_cursocapacitacion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='estado_civil',
            field=models.CharField(choices=[('Soltero/a', 'Soltera/a'), ('Casado/a', 'Casada/a'), ('Divorciado/a', 'Divorciada/a'), ('Viudo/a', 'Viuda/a'), ('Unión Libre', 'Unión Libre')], max_length=30),
        ),
    ]
