# Generated by Django 6.0.1 on 2026-01-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0012_alter_datospersonales_estado_civil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='estado_civil',
            field=models.CharField(choices=[('Soltera/o', 'Soltera/o'), ('Casada/o', 'Casado/a'), ('Divorciada/o', 'Divorciado/a'), ('Viuda/o', 'Viudo/a'), ('Unión Libre', 'Unión Libre')], max_length=30),
        ),
    ]
