# Generated by Django 6.0.1 on 2026-01-28 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0014_alter_datospersonales_estado_civil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='estado_civil',
            field=models.CharField(choices=[('Soltero/a', 'Soltero/a'), ('Casado/a', 'Casado/a'), ('Divorciado/a', 'Divorciado/a'), ('Viudo/a', 'Viudo/a'), ('Unión Libre', 'Unión Libre')], max_length=30),
        ),
    ]
