# Generated by Django 6.0.1 on 2026-01-30 21:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0015_alter_datospersonales_estado_civil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productolaboral',
            name='archivo',
            field=models.FileField(blank=True, help_text='Documentación del proyecto (Solo archivos PDF)', null=True, upload_to='proyectos/archivos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
