# Generated by Django 6.0.1 on 2026-01-31 02:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0016_alter_productolaboral_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventagarage',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Publicación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='estado',
            field=models.CharField(choices=[('Nuevo', 'Nuevo'), ('Bueno', 'Bueno'), ('Regular', 'Regular')], max_length=50),
        ),
    ]
