# Generated by Django 6.0.1 on 2026-01-31 03:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0017_ventagarage_fecha_publicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventagarage',
            name='fecha_publicacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Publicación'),
        ),
    ]
