# Generated by Django 6.0.1 on 2026-01-31 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0018_alter_ventagarage_fecha_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconocimiento',
            name='certificado_pdf',
            field=models.FileField(blank=True, help_text='Sube el diploma o certificado en formato PDF', null=True, upload_to='reconocimientos/certificados/'),
        ),
    ]
