# Generated by Django 6.0.1 on 2026-02-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0019_reconocimiento_certificado_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datospersonales',
            name='cedula',
            field=models.CharField(max_length=13, unique=True, verbose_name='Cédula / ID'),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='nacionalidad',
            field=models.CharField(default='Ecuatoriano', max_length=50),
        ),
    ]
