# Generated by Django 6.0.1 on 2026-02-02 22:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0020_alter_datospersonales_cedula_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencialaboral',
            name='certificado',
            field=models.FileField(blank=True, null=True, upload_to='experiencia/certificados/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Certificado Laboral (PDF)'),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='email_empresa',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email Empresa'),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='nombre_contacto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Contacto'),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='sitio_web_empresa',
            field=models.URLField(blank=True, max_length=100, null=True, verbose_name='Sitio Web'),
        ),
        migrations.AddField(
            model_name='experiencialaboral',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Teléfono Contacto'),
        ),
    ]
