# Generated by Django 6.0.1 on 2026-02-02 22:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0021_experiencialaboral_certificado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconocimiento',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción del Reconocimiento'),
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='nombre_contacto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Contacto Auspicia'),
        ),
        migrations.AddField(
            model_name='reconocimiento',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Teléfono Contacto Auspicia'),
        ),
        migrations.AlterField(
            model_name='reconocimiento',
            name='certificado_pdf',
            field=models.FileField(blank=True, help_text='Sube el diploma o certificado en formato PDF', null=True, upload_to='reconocimientos/certificados/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
