# Generated by Django 6.0.1 on 2026-02-02 22:28

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0022_reconocimiento_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursocapacitacion',
            options={'ordering': ['-fecha_fin'], 'verbose_name_plural': 'Cursos y Formaciones'},
        ),
        migrations.RemoveField(
            model_name='cursocapacitacion',
            name='fecha_realizacion',
        ),
        migrations.AddField(
            model_name='cursocapacitacion',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción del Curso'),
        ),
        migrations.AddField(
            model_name='cursocapacitacion',
            name='email_empresa',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Email Empresa Patrocinadora'),
        ),
        migrations.AddField(
            model_name='cursocapacitacion',
            name='fecha_fin',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Fin'),
        ),
        migrations.AddField(
            model_name='cursocapacitacion',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Inicio'),
        ),
        migrations.AddField(
            model_name='cursocapacitacion',
            name='nombre_contacto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Contacto (Auspicia)'),
        ),
        migrations.AddField(
            model_name='cursocapacitacion',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Teléfono Contacto'),
        ),
        migrations.AlterField(
            model_name='cursocapacitacion',
            name='certificado_pdf',
            field=models.FileField(blank=True, help_text='Sube el certificado del curso en formato PDF', null=True, upload_to='cursos/certificados/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
