# Generated by Django 6.0.1 on 2026-02-02 22:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0023_alter_cursocapacitacion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productolaboral',
            name='registro_id',
        ),
        migrations.AlterField(
            model_name='productolaboral',
            name='archivo',
            field=models.FileField(blank=True, help_text='Sube documentación o capturas (Formatos permitidos: PDF, JPG, JPEG, PNG)', null=True, upload_to='proyectos/archivos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Archivo o Evidencia'),
        ),
    ]
