# Generated by Django 6.0.1 on 2026-02-02 22:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0024_remove_productolaboral_registro_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ventagarage',
            options={'ordering': ['-fecha_publicacion'], 'verbose_name_plural': 'Venta de Garage'},
        ),
        migrations.RemoveField(
            model_name='estudiorealizado',
            name='certificado_pdf',
        ),
        migrations.AddField(
            model_name='estudiorealizado',
            name='archivo',
            field=models.FileField(blank=True, help_text='Sube documentación o capturas (Formatos permitidos: PDF, JPG, JPEG, PNG)', null=True, upload_to='proyectos/archivos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Archivo o Evidencia'),
        ),
        migrations.AddField(
            model_name='estudiorealizado',
            name='descripcion',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
