# Generated by Django 6.0.1 on 2026-02-02 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0025_alter_ventagarage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiorealizado',
            name='descripcion',
            field=models.TextField(default='Sin descripción de funciones'),
        ),
    ]
