# Generated by Django 6.0.1 on 2026-02-02 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0026_alter_estudiorealizado_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiorealizado',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción / Logros'),
        ),
    ]
