# Generated by Django 6.0.1 on 2026-02-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0027_alter_estudiorealizado_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Recurso')),
                ('clasificador', models.CharField(max_length=100, verbose_name='Clasificador / Categoría')),
                ('descripcion', models.TextField(max_length=500, verbose_name='Descripción')),
                ('visible', models.BooleanField(default=True, verbose_name='Mostrar en CV')),
            ],
            options={
                'verbose_name_plural': 'Productos Académicos',
            },
        ),
    ]
